<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="ProjectMahmut.WebForm1" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server" aria-atomic="False" aria-disabled="False" aria-dropeffect="none" dir="auto">
        <p style="margin-left: 680px">
            UNIPA SIRKETI</p>
        <p>
            Ogrenci Bilgi sistemi(Duzeltmeler yapılamaz)</p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource2" EnableModelValidation="True" ForeColor="#333333" GridLines="None" Height="81px" Width="247px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="OgrenciAd" HeaderText="OgrenciAd" SortExpression="OgrenciAd" />
                <asp:BoundField DataField="OgrenciSoyad" HeaderText="OgrenciSoyad" SortExpression="OgrenciSoyad" />
                <asp:BoundField DataField="OgrenciNo" HeaderText="OgrenciNo" SortExpression="OgrenciNo" />
                <asp:BoundField DataField="TC" HeaderText="TC" SortExpression="TC" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:OgrenciConnectionString %>" SelectCommand="SELECT * FROM [OgrenciTablosu]"></asp:SqlDataSource>
        <br />
        <asp:Label ID="Label1" runat="server" Text="Göncel Tablo, göncel veriler görmek için sayfa kapatn ve yine açın lütfen"></asp:Label>
        <asp:GridView ID="GridView2" runat="server" AllowSorting="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataSourceID="SqlDataSource3" EnableModelValidation="True">
            <Columns>
                <asp:BoundField DataField="OgrenciId" HeaderText="OgrenciId" SortExpression="OgrenciId" />
                <asp:BoundField DataField="OgrenciAd" HeaderText="OgrenciAd" SortExpression="OgrenciAd" />
                <asp:BoundField DataField="OgrenciSoyad" HeaderText="OgrenciSoyad" SortExpression="OgrenciSoyad" />
                <asp:BoundField DataField="OgrenciNo" HeaderText="OgrenciNo" SortExpression="OgrenciNo" />
                <asp:BoundField DataField="DersKodu" HeaderText="DersKodu" SortExpression="DersKodu" />
                <asp:BoundField DataField="DersAdı" HeaderText="DersAdı" SortExpression="DersAdı" />
            </Columns>
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <RowStyle BackColor="White" ForeColor="#003399" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:OgrenciConnectionString %>" SelectCommand="SELECT Baglama.OgrenciId, OgrenciTablosu.OgrenciAd, OgrenciTablosu.OgrenciSoyad, OgrenciTablosu.OgrenciNo, Dersler.DersKodu, Dersler.DersAdı FROM Baglama INNER JOIN Dersler ON Baglama.Id = Dersler.Id INNER JOIN OgrenciTablosu ON Baglama.Id = OgrenciTablosu.Id"></asp:SqlDataSource>
        <p style="height: 36px; width: 375px; margin-left: 40px">
            Dersler(MsSQL ile baglı Duzeltilebilir)<br />
        </p>
        <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" DefaultMode="Edit" EnableModelValidation="True" EnablePagingCallbacks="True" EnableTheming="True" GridLines="Horizontal" Height="245px" OnPageIndexChanging="DetailsView1_PageIndexChanging" Width="421px">
            <Fields>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="DersKodu" HeaderText="DersKodu" SortExpression="DersKodu" />
                <asp:BoundField DataField="DersAdı" HeaderText="DersAdı" SortExpression="DersAdı" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:OgrenciConnectionString %>" DeleteCommand="DELETE FROM [Dersler] WHERE [Id] = @original_Id AND (([DersKodu] = @original_DersKodu) OR ([DersKodu] IS NULL AND @original_DersKodu IS NULL)) AND (([DersAdı] = @original_DersAdı) OR ([DersAdı] IS NULL AND @original_DersAdı IS NULL))" InsertCommand="INSERT INTO [Dersler] ([Id], [DersKodu], [DersAdı]) VALUES (@Id, @DersKodu, @DersAdı)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Dersler]" UpdateCommand="UPDATE [Dersler] SET [DersKodu] = @DersKodu, [DersAdı] = @DersAdı WHERE [Id] = @original_Id AND (([DersKodu] = @original_DersKodu) OR ([DersKodu] IS NULL AND @original_DersKodu IS NULL)) AND (([DersAdı] = @original_DersAdı) OR ([DersAdı] IS NULL AND @original_DersAdı IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_Id" Type="Int32" />
                <asp:Parameter Name="original_DersKodu" Type="String" />
                <asp:Parameter Name="original_DersAdı" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="DersKodu" Type="String" />
                <asp:Parameter Name="DersAdı" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="DersKodu" Type="String" />
                <asp:Parameter Name="DersAdı" Type="String" />
                <asp:Parameter Name="original_Id" Type="Int32" />
                <asp:Parameter Name="original_DersKodu" Type="String" />
                <asp:Parameter Name="original_DersAdı" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <p>
        <asp:Label ID="lblUyari" runat="server" Text="Program Kurulum yaparken sorun yaşadım, zellikle TELERİK ile ilgili çok sorun yaşadım, kurlulum düzelince daha hızlı ilerliceğim" Visible="True"></asp:Label>
        </p>
        <p>
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Label Visible" />
        </p>
    </form>
</body>
</html>
